# Generated by Django 4.2 on 2023-05-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_MKD', models.SmallIntegerField()),
                ('number_people', models.PositiveIntegerField()),
                ('yard_area', models.FloatField()),
                ('percentage_of_vote', models.FloatField()),
                ('participation_in_municipal', models.BooleanField()),
                ('point', models.SmallIntegerField()),
                ('link_to_crt', models.CharField(max_length=255)),
                ('link_to_protocol', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Application_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.application')),
                ('type_jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.type_jobs')),
            ],
        ),
        migrations.CreateModel(
            name='Application_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.address')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.ManyToManyField(through='hello.Application_address', to='hello.address'),
        ),
        migrations.AddField(
            model_name='application',
            name='types',
            field=models.ManyToManyField(through='hello.Application_type', to='hello.type_jobs'),
        ),
    ]
